[package]
name = "Titantic"
version = "0.1.0"
edition = "2021"

[dependencies]
zmq = "0.10.0"
thiserror = "2.0.8"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
lazy_static = "1.5.0"
ctrlc = "3.4.5"
log = "0.4.22"
hex = "0.4.3"
